name: GitHub Pages Deploy
on:
  push:
    branches:
    - main
jobs:
  github-pages-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sh build-catalog.sh
    - uses: github-actions-x/commit@v2.8
      with:
        commit-message: Update project catalog
        files: eclipse-projects.setup
        name: Arlo O'Keeffe
        email: tiger@k5d.de
