name: GitHub Pages Deploy
on:
  push:
    branches:
    - master
jobs:
  github-pages-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sh build-catalog.sh
    - uses: github-actions-x/commit@v2.5
      with:
        commit-message: Update project catalog
        files: arlos-projects.setup
        name: Arlo O'Keeffe
        email: tiger@k5d.de
